### ISSUE TITLE
Expected format

### ISSUE THREAD

**Issue by Giovani-Merlin** [bleugreen/deeprhythm#2]
Hello, first, thank you for the easy-to-use library, but it's missing some documentation.

Can I use MP3 files? Which sampling rate should I use? What format is expected?
I'm doing it for some electronic music, where the bpm is super clear, for some of them It has great precision and for others I have the bpm 1/2 more or less.

Can you give me some hint?

**Comment by bleugreen** [comment]
- Yes, mp3 files should work, it loads audio with `librosa.load()` which supports mp3, flac, wav, ogg, vorbis, etc.
- Input audio is loaded and processed at 22050Hz, so as long as its not significantly less than that it should be fine
- The "Off by 1/2" is a tricky one, since a quarter notes at 120 bpm look the same as eighth notes at 60bpm. In the original paper on the model, the authors use two accuracy measures: Acc1 (within threshold of actual tempo) and Acc2 (within threshold of a multiple of actual tempo). Their model had an Acc1 / Acc2 of 74 / 92. In my training & subsequent tuning, I've gotten my model to 95.9 / 96.5, reducing these errors significantly. However, it's an estimator trained on limited data, and it's not perfect. In my experience so far, it's pretty trivial to just multiply / divide the BPM by 2 when I notice it's off, or even treat each song's tempo as an array of its multiples (i.e. [65, 130, 260]) when tempo-matching larger sets of data

**Comment by Giovani-Merlin** [comment]
Tottally understood, I will add some basic logic in the output to counter-effect it. Thank you!
